version: '3.8'

services:
  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

  app:
    build:
      context: .
    volumes:
      - ./:/var/www
    environment:
      - "PHP_FPM_LISTEN=app:9000"

  worker:
    build:
      context: .
    command: php bin/worker
    volumes:
      - ./:/var/www
    depends_on:
      - queue

  queue:
    image: redis:alpine
    ports:
      - "6379:6379"
